"""
-Performance Join
   Quando uma consulta contendo JOIN é executada, o SQLite recisa comparar os valores definidos na condição de junção para identificar quais registros possuem relacionamento entre si. Quanto maior a quantidade de registros envolvidos, maior será o trabalho necessário para localizar essas correspondências. Por esse motivo, o desempenho de um JOIN está diretamente relacionado ao volume de dados presente nas tabelas participantes.

   O fator que mais influencia a performance de um JOIN é a existência de índices nas colunas utilizadas na condição de relacionamento. Quando uma coluna possui índice, o SQLite consegue localizar rapidamente os registros correspondentes sem precisar percorrer toda a tabela. Já quando não existe índice, o banco frequentemente precisa realizar uma varredura completa (Full Table Scan), examinando linha por linha até encontrar as correspondências necessárias. Em tabelas pequenas essa diferença pode passar despercebida, mas em bases de dados maiores ela pode representar uma diferença de segundos ou até minutos de execução.

   Em bancos de dados relacionais, o cenário ideal ocorre quando os JOINs são realizados entre chaves primárias e chaves estrangeiras. Como as chaves primárias normalmente já possuem índices automaticamente e as chaves estrangeiras costumam ser indexadas pelo desenvolvedor, o banco consegue localizar os registros relacionados de forma extremamente eficiente. Esse é o padrão mais comum em sistemas reais e também aquele para o qual os mecanismos de otimização dos bancos de dados foram projetados.

   O tipo de JOIN utilizado também influencia a quantidade de dados processados. O INNER JOIN retorna apenas os registros que possuem correspondência nas duas tabelas, produzindo normalmente conjuntos de resultados menores. O LEFT JOIN preserva todos os registros da tabela à esquerda da junção, mesmo quando não existe correspondência na tabela da direita, o que pode resultar em um volume maior de dados retornados. Já o CROSS JOIN gera um produto cartesiano, combinando cada linha de uma tabela com todas as linhas da outra. Dependendo do tamanho das tabelas envolvidas, isso pode produzir quantidades extremamente grandes de registros e impactar significativamente o desempenho.

   A presença de filtros também pode influenciar positivamente a performance. Quando uma consulta utiliza cláusulas como WHERE, o SQLite frequentemente consegue reduzir o número de registros analisados antes mesmo de executar parte do JOIN. Isso diminui a quantidade de comparações necessárias e reduz o custo total da consulta.
"""